#################################################
#Made by Adventquest							#
#Keep Stock working   					        #
#################################################


##Particles showing the position of the storage
execute as @e[type=minecraft:chest_minecart,tag=KeepOriginalData] at @s run function att2:gameplay/dahal/action/spell20/particle_effect
##follow_owner
execute as @e[type=minecraft:chest_minecart,tag=invminecarts.invisible_minecart] unless entity @s[scores={SUMMON_TIMER=1..}] run function att2:gameplay/dahal/action/spell20/follow_owner
##Remove the chest_minecart generated by this spell casting
execute at @a as @e[type=minecraft:chest_minecart,tag=invminecarts.invisible_minecart,tag=!NewInvo,distance=..10] run function att2:gameplay/dahal/action/spell20/chest_minecart_data_compare
##Recycling placement
execute at @a[scores={recycle_set=1}] as @e[type=minecraft:armor_stand,tag=Recycler,distance=..3] run function att2:gameplay/dahal/action/spell20/recycle_set
execute as @a[scores={recycle_set=0}] at @s run function att2:gameplay/dahal/action/spell20/recycle_back 


